version: "3.7"

services:
  rabbit:
    container_name: rabbit
    image: "rabbitmq:3.7-management"
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    image: howtocards/preview-queue/preview-queue
    container_name: queue
    restart: always
    entrypoint: /queue
    command:
      - "--rabbit.host=rabbit"
    ports:
      - "8080:8080"
