swagger: "2.0"

consumes:
  - application/json
produces:
  - application/json

info:
  version: 0.1.0
  title: Facade.
  description: A queuing wrapper.

basePath: /

schemes:
  - http

definitions:
  UserRender:
    type: object
    required:
      - user
      - callback
    properties:
      user:
        $ref: "#/definitions/userPath"
      callback:
        $ref: "#/definitions/url"
      extra:
        $ref: '#/definitions/extra'
    example:
      user: "@sergeysova"
      callback: "/preview/user/@sergeysova"
      extra:
        foo: bar
        baz: true
  
  CardRender:
    type: object
    required:
      - card
      - callback
    properties:
      card:
        $ref: '#/definitions/cardPath'
      callback:
        $ref: '#/definitions/url'
      extra:
        $ref: '#/definitions/extra'
    example: 
      card: "1902"
      callback: "/preview/card/1902"
      extra:
        foo: bar
        baz: true

  url:
    type: string

  userPath:
    type: string
    description: Username to identify user. Should be prefixed @
    minLength: 1
    maxLength: 200

  cardPath:
    type: string
    description: Id or card slug
    minLength: 1
    maxLength: 200

  extra:
    type: object
    description: Optional object with any information for render worker

  Error:
    type: object
    required:
      - code
      - message
    properties:
      code:
        description: Either same as HTTP Status Code.
        type: integer
        format: int32
      message:
        type: string

responses:
  NoContent:
    description: The server successfully processed the request and is not returning any content.

  GenericError:
    description: Generic error response.
    schema:
      $ref: "#/definitions/Error"

paths:
  /render/user:
    post:
      description: Render user preview
      operationId: renderUser
      parameters:
        - name: body
          required: true
          in: body
          schema:
            $ref: "#/definitions/UserRender"
        - { $ref: "#/parameters/appName" }
      responses:
        "200": { $ref: "#/responses/NoContent" }
        default: { $ref: "#/responses/GenericError" }
  
  /render/card:
    post:
      description: Render preview and snapshot for card
      operationId: renderCard
      parameters:
        - name: body
          required: true
          in: body
          schema:
            $ref: '#/definitions/CardRender'
        - { $ref: "#/parameters/appName" }
      responses:
        "200": { $ref: "#/responses/NoContent" }
        default: { $ref: "#/responses/GenericError" }

parameters:
  appName:
    name: appName
    in: query
    type: string
    description: Name of the app that call api

